# .github/dependabot.yml
version: 2

# Security updates:
# - Dependabot will open PRs automatically when GitHub Security Advisories flag vulnerabilities.
# - Keep daily schedule; security PRs will arrive as advisories are published.
# - Groups below include a 'security' bucket so security updates are clearly labeled/bundled.

updates:
  # 1) NPM (root)
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "America/Denver"
    open-pull-requests-limit: 50
    rebase-strategy: auto
    labels: ["deps", "automerge"]
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]

  # 2) GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "09:05"
      timezone: "America/Denver"
    open-pull-requests-limit: 50
    rebase-strategy: auto
    labels: ["deps", "automerge"]
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]

  # 3) Docker — .portainer/Dockerfile
  - package-ecosystem: docker
    directory: "/.portainer"
    schedule:
      interval: daily
      time: "09:10"
      timezone: "America/Denver"
    open-pull-requests-limit: 50
    rebase-strategy: auto
    labels: ["deps", "automerge"]
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]

  # 4) Docker — markdown_gateway/Dockerfile
  - package-ecosystem: docker
    directory: "/markdown_gateway"
    schedule:
      interval: daily
      time: "09:12"
      timezone: "America/Denver"
    open-pull-requests-limit: 50
    rebase-strategy: auto
    labels: ["deps", "automerge"]
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
