[settings]
idiomatic_version_file_enable_tools = ["node"]
[tools]
node = "20"
npm = "latest"

[tasks.build]
run = "npx @11ty/eleventy"
description = "Build Eleventy static site"

[tasks.dev]
run = "npx @11ty/eleventy --serve"
description = "Start Eleventy dev server"

[tasks.test]
run = "node --test"
description = "Run Node.js test suite"
