#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
#  setup-tailwind-safe.sh  —  Tailwind-4 + Eleventy bootstrap
#  (does nothing twice, backs up anything it might overwrite)
# ─────────────────────────────────────────────────────────────
set -euo pipefail

green() { printf "\033[0;32m%s\033[0m\n" "$*"; }
yellow() { printf "\033[0;33m%s\033[0m\n" "$*"; }

# 1 ▸ plugin install (skip if already present)
if grep -q '"eleventy-plugin-tailwindcss-4"' package.json 2>/dev/null; then
  green "✓ eleventy-plugin-tailwindcss-4 already in package.json"
else
  yellow "→ installing eleventy-plugin-tailwindcss-4 …"
  npm install -D eleventy-plugin-tailwindcss-4
fi

# 2 ▸ directory scaffold
mkdir -p src/assets/css

# 3 ▸ tailwind entry file
if [[ -f src/assets/css/tailwind.css ]]; then
  green "✓ src/assets/css/tailwind.css already exists"
else
  yellow "→ creating src/assets/css/tailwind.css"
  cat > src/assets/css/tailwind.css <<'EOF'
@tailwind base;
@tailwind components;
@tailwind utilities;
/* put any tiny tweaks below */
EOF
fi

# 4 ▸ preserve old main.css (rename once)
if [[ -f src/assets/css/main.css ]]; then
  if [[ -f src/assets/css/brand.css ]]; then
    green "✓ brand.css already present; main.css left intact"
  else
    yellow "→ moving existing main.css → brand.css"
    mv src/assets/css/main.css src/assets/css/brand.css
  fi
fi

# 5 ▸ tailwind.config.js with palette & fonts
if [[ -f tailwind.config.js ]]; then
  green "✓ tailwind.config.js already exists (not overwritten)"
else
  yellow "→ writing tailwind.config.js"
  cat > tailwind.config.js <<'EOF'
/** Tailwind v4 config — generated by setup-tailwind-safe.sh */
export default {
  content: ["./src/**/*.{njk,md,html}"],
  theme: {
    extend: {
      colors: {
        cerulean:  "#0698e0",
        danube:    "#60a0cd",
        malachite: "#10ea30",
        shamrock:  "#0dbb25",
        "text-light": "#f0f0f0",
        "text-dark":  "#1a1a1a",
        "bg-dark":    "#0f0f0f"
      },
      fontFamily: {
        heading: ["'Bebas Neue'", "sans-serif"],
        body:    ["'Roboto'",     "sans-serif"]
      }
    }
  },
  plugins: [require("@tailwindcss/typography")]
};
EOF
fi

green "✔  Tailwind bootstrap done — restart with:  npx eleventy --serve"
