id: hb-guard-fix
name: Hardened stream guard for LLM/CI shells
intent: |
  Analyze the environment (LLM pseudo-PTY, CI, container, shells, toolchain),
  install the most robust console stream guard, and prove correctness via TDD.
owner: hypebrut
triggers:
  - manual
  - on_change:
      paths:
        - utils/scripts/setup/env-bootstrap.sh
        - .araca/tasks/hb-guard-fix.yaml
        - scripts/araca/hb-guard-fix.sh
requirements:
  shell: bash
  tools:
    - mkfifo
    - perl|python3
plan:
  - step: analyze
    run: scripts/araca/hb-guard-fix.sh analyze
  - step: patch_bootstrap
    run: scripts/araca/hb-guard-fix.sh patch
  - step: write_shims
    run: scripts/araca/hb-guard-fix.sh write-shims
  - step: test_guard
    run: scripts/araca/hb-guard-fix.sh test
  - step: report
    run: scripts/araca/hb-guard-fix.sh report
success_criteria:
  - 'All tests under test/hb_guard/*.t exit 0'
  - 'Sourcing env-bootstrap.sh in a fresh non-interactive shell prints nothing on stdout and only comment-prefixed lines on stderr'
  - 'Minified/one-line payloads are soft-wrapped with [HBWRAP …] markers at configured width'
  - 'Hazardous control bytes are suppressed with a single [HBBIN suppressed …] line; raw bytes land in sidecar logs'
  - 'hb_disarm fully restores FDs; no stuck filters; FIFOs are removed'
outputs:
  - logs: '/tmp/hype_logs/hb.*.log'
  - summary: 'var/hb_guard_summary.json'
rollback:
  run: scripts/araca/hb-guard-fix.sh rollback
