#!/usr/bin/env bash
# Self-restore bootstrap for LLM-safe guardrails.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Create/refresh BASH_ENV
cat > "$repo_root/.llm-bash-env" <<EOF
# Auto-generated by llm-bootstrap.sh
if [[ "\${LLM_HIJACK_DISABLE:-}" != "1" ]]; then
  source "$repo_root/scripts/llm-hijack.sh"
fi
EOF

# Install git hooks to self-restore
for hook in post-checkout post-merge; do
  hook_path="$repo_root/.git/hooks/$hook"
  cat > "$hook_path" <<'EOH'
#!/usr/bin/env bash
bash scripts/llm-bootstrap.sh >/dev/null 2>&1
EOH
  chmod +x "$hook_path"
done

# Prepend repo bin to PATH for interactive shells
if [[ $- == *i* ]] && [[ ":$PATH:" != *":$repo_root/bin:"* ]]; then
  export PATH="$repo_root/bin:$PATH"
fi

