# .github/workflows/dependabot-auto-merge.yml
name: Dependabot Auto-Merge (Autonomous)

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Auto-approve to satisfy branch protection that requires at least one approval.
      # NOTE: If CODEOWNERS-specific reviews are required, ensure this bot/user is a valid code owner.
      - name: Approve PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/approve-pull-request@v5
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          review-message: "Auto-approving Dependabot PR"

      # Enable native auto-merge for ALL Dependabot updates (including majors).
      # GitHub will merge once required checks pass and protections are satisfied.
      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
